apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-neo4j-connector
spec:
  selector:
    matchLabels:
      app: kafka-neo4j-connector
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-neo4j-connector
    spec:
      containers:
      - name: kafka-neo4j-connector
        image: veedata/kafka-neo4j-connect:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: KAFKA_TOPIC
          value: "my-topic"
        - name: NEO4J_HOST
          value: "neo4j-service"
        - name: NEO4J_USERNAME
          value: "neo4j"
        - name: NEO4J_PASSWORD
          value: "project2phase2"
        ports:
        - containerPort: 8083