neo4j:
  name: neo4j-standalone
  resources:
    cpu: "2"
    memory: "4Gi"

  password: "project2phase2"


volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 4Gi
env:
  NEO4J_PLUGINS: '["graph-data-science"]'
config:
  dbms.security.procedures.unrestricted: "gds.*"